/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onycom_vps_VPSNativeLib */

#ifndef _Included_com_onycom_vps_VPSNativeLib
#define _Included_com_onycom_vps_VPSNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onycom_vps_VPSNativeLib
 * Method:    Start
 * Signature: 
 */
JNIEXPORT void JNICALL Java_com_onycom_vps_VPSNativeLib_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_onycom_vps_VPSNativeLib
 * Method:    Stop
 * Signature: 
 */
JNIEXPORT void JNICALL Java_com_onycom_vps_VPSNativeLib_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_onycom_vps_VPSNativeLib
 * Method:    GetLastScene
 * Signature: 
 */
JNIEXPORT jint JNICALL Java_com_onycom_vps_VPSNativeLib_GetLastScene
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
